
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: pm2 stop 1
      - name: Run a multi-line script
        run: |
          echo "hola mundo extra" >> hola.txt
          pm2 start 1
